### PR TITLE
Updates for using webpack 5. Please review

### PR DESCRIPTION
**Pull request by petrushy**
A PR for building using webpack 5. It is working but please review, I am by no means an expert in this area. 

Especially regarding the import of .css in the src/index.js I think is likely not the right way to do it, but cannot find another way without a protest regarding the exports in cesium:

    import "../dist/Widgets/widgets.css"

### CODE REVIEW

**Comment by goldenram** [comment]
Any progress made on this?  We are trying to update our project to use Webpack 5 and the Cesium library is the only library blocking completing that task.  Thanks!

**Comment by petrushy** [comment]
Hi, It works it seems and I also realized there is another PR with webpack 5 https://github.com/CesiumGS/cesium-webpack-example/pull/23

But would be good if someone with more insight reviewed this / that.

**Comment by boeckMt** [comment]
Hey I think there are now three PR's with similar stuff. Maybe someone can link/merge #28. #23, #25 together?

**Comment by maylortaylor** [comment]
I am getting a `ReferenceError: __dirname is not defined` in the `index.cjs` file at the point below:
module.exports = __webpack_require__("../../node_modules/cesium sync recursive")(path.join(
  __dirname,
  "Build/CesiumUnminified/index.cjs"
));

**Comment by jjspace** [comment]
replaced by https://github.com/CesiumGS/cesium-webpack-example/pull/52

**Pull request closed without merging**
