### PR TITLE
Updated CopyWebpackPlugin

### PR DESCRIPTION
**Pull request by sdhani**
Hi! I noticed that the CopyWebpackPlugin has now been [updated](https://webpack.js.org/plugins/copy-webpack-plugin/) to take in a pattern and thought I'd make the change here. Hope it's helpful!

### CODE REVIEW

**Comment by sanjeetsuhag** [comment]
@sdhani Thanks for the PR! The build on this branch is failing for me. There's a couple of additional changes that need to be made before this can get merged:

- [ ] Update `copy-webpack-plugin` to the latest version in [package.json](https://github.com/sdhani/cesium-webpack-example/blob/copy-webpack-update/package.json). The latest version is [6.0.3](https://www.npmjs.com/package/copy-webpack-plugin).
- [ ] Update plugin syntax in [webpack.release.config.json](https://github.com/sdhani/cesium-webpack-example/blob/copy-webpack-update/webpack.release.config.js).

**Comment by sdhani** [comment]
Great catch @sanjeetsuhag! It should be all good now 😄 

- [x] Update copy-webpack-plugin to the latest version in package.json. The latest version is 6.0.3.
- [x] Update plugin syntax in webpack.release.config.json.

**Comment by sanjeetsuhag** [comment]
Now it works perfectly! Thanks again for the contribution @sdhani!

**Comment by sanjeetsuhag** [comment]
@sdhani Bit of an oversight on my part, but we require all contributors to sign the Contributors License Agreement. Please follow the directions [here](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) to add yourself as a contributor.

**Pull request merged**
